### ISSUE TITLE
建议添加其它操作系统

### ISSUE THREAD

**Issue by sshuair** [QingyaFan/kubernetes-cluster-creator#7]
- ubuntu
- macos
- windows

**Comment by QingyaFan** [comment]
macos和windows，应该一般用于开发测试，并不是要用它们来搭建开发环境，而搭建开发环境有更好minikube，因此，没有必要添加macos和windows的支持。至于ubuntu，是有必要支持的，可以作为后续的一个milestone。

如果急用或者感兴趣，欢迎提交PR。
